### PR TITLE
fix travis test suite

### PR DESCRIPTION
**Pull request by Ma27**
this PR adds symfony 2.7 to the test matrix in travis ci

### CODE REVIEW

**Comment by christoph-hautzinger** [comment]
Thanks for your pull request! Actually I tried to get travis running but it wasn't that simple than it looks like!? Tried many configurations but everything was weird :D. do you have experience with travisci? probably I can find some time at the weekend to address this issue again :)

**Comment by Ma27** [comment]
Yes I do. Not that much, but at least a little bit ;)
I'll check this out when I've got time and see where I can help

**Comment by Ma27** [comment]
squashed my commits. I'm not sure, but this should travis make work. If not, I'll look for a solution tomorrow

**Comment by Ma27** [comment]
ok, just fixed the .travis.yml file.
If something fails now, I'm pretty sure that it is a version related issue..

**Comment by christoph-hautzinger** [comment]
thanks man! :) :)

**Pull request merged**
